/**
 * Mock category data for testing and demo purposes
 */

import type { CategoryBundle } from './CategoryTilesGrid';

export const mockCategoryBundles: CategoryBundle[] = [
  {
    key: 'duplicates',
    title: 'Duplicados',
    icon: null, // Will be auto-generated by CategoryTilesGrid
    count: 150,
    locked: true, // Pro feature
  },
  {
    key: 'blurry',
    title: 'Borrosas',
    icon: null,
    count: 42,
    locked: false,
  },
  {
    key: 'screenshots',
    title: 'Pantallazos',
    icon: null,
    count: 238,
    locked: false,
  },
  {
    key: 'burst',
    title: 'En ráfaga',
    icon: null,
    count: 89,
    locked: false,
  },
  {
    key: 'whatsapp',
    title: 'WhatsApp/Telegram',
    icon: null,
    count: 567,
    locked: false,
  },
  {
    key: 'long_videos',
    title: 'Vídeos largos',
    icon: null,
    count: 12,
    locked: false,
  },
  {
    key: 'large_files',
    title: 'Archivos grandes',
    icon: null,
    count: 34,
    locked: false,
  },
  {
    key: 'documents',
    title: 'Documentos/Recibos',
    icon: null,
    count: 78,
    locked: false,
  },
];

/**
 * Get category bundles with i18n support
 */
export const getCategoryBundles = (t: (key: string) => string): CategoryBundle[] => {
  return [
    {
      key: 'duplicates',
      title: t('categories.duplicates'),
      icon: null,
      count: 150,
      locked: true,
    },
    {
      key: 'blurry',
      title: t('categories.blurry'),
      icon: null,
      count: 42,
      locked: false,
    },
    {
      key: 'screenshots',
      title: t('categories.screenshots'),
      icon: null,
      count: 238,
      locked: false,
    },
    {
      key: 'burst',
      title: t('categories.burst'),
      icon: null,
      count: 89,
      locked: false,
    },
    {
      key: 'whatsapp',
      title: t('categories.whatsapp'),
      icon: null,
      count: 567,
      locked: false,
    },
    {
      key: 'long_videos',
      title: t('categories.long_videos'),
      icon: null,
      count: 12,
      locked: false,
    },
    {
      key: 'large_files',
      title: t('categories.large_files'),
      icon: null,
      count: 34,
      locked: false,
    },
    {
      key: 'documents',
      title: t('categories.documents'),
      icon: null,
      count: 78,
      locked: false,
    },
  ];
};
